### PR TITLE
Test for `getManifest()`

### PR DESCRIPTION
**Pull request by RobinTail**
Challenge: bun is unable to unmock a mocked module (fs in this case).
Workaround: globally available `mocks` dir with a `readerMock` used by the test of `getManifest()`

### CODE REVIEW

**Comment by RobinTail** [comment]
bun issue — addressing in #19

**Review by RobinTail — COMMENTED** [review]
nice

**Comment by Jarred-Sumner** [comment]
> Challenge: bun is unable to unmock a mocked module (fs in this case).

Have you tried `jest.clearAllMocks()`? Worst case you might need to do that and `delete require.cache["fs"]` but I don't think both are necessary

**Comment by RobinTail** [comment]
Here is no `jest`, but I'll try the suggested approach with a similar method of `bun` — thank you @Jarred-Sumner

**Pull request merged**
